/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.stisipolrajahaji.feederclient;

import id.ac.stisipolrajahaji.feederclient.perkuliahan.KelasPerkuliahanFrame;
import id.ac.stisipolrajahaji.feederclient.perkuliahan.MatakuliahPerkuliahanFrame;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author admin
 */
public class MainFrame extends javax.swing.JFrame {    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dekstopPaneChild = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuMatakuliahPerkuliahan = new javax.swing.JMenuItem();
        menuKelasPerkuliahan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Feeder Client");
        setExtendedState(6);
        setName("MainFrame"); // NOI18N
        setResizable(false);

        javax.swing.GroupLayout dekstopPaneChildLayout = new javax.swing.GroupLayout(dekstopPaneChild);
        dekstopPaneChild.setLayout(dekstopPaneChildLayout);
        dekstopPaneChildLayout.setHorizontalGroup(
            dekstopPaneChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        dekstopPaneChildLayout.setVerticalGroup(
            dekstopPaneChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Perkuliahan");

        menuMatakuliahPerkuliahan.setText("Matakuliah");
        menuMatakuliahPerkuliahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMatakuliahPerkuliahanActionPerformed(evt);
            }
        });
        jMenu2.add(menuMatakuliahPerkuliahan);

        menuKelasPerkuliahan.setText("Kelas Perkuliahan");
        menuKelasPerkuliahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKelasPerkuliahanActionPerformed(evt);
            }
        });
        jMenu2.add(menuKelasPerkuliahan);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dekstopPaneChild)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dekstopPaneChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuKelasPerkuliahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKelasPerkuliahanActionPerformed
        
        KelasPerkuliahanFrame frmKelasPerkuliahan = new KelasPerkuliahanFrame();
        frmKelasPerkuliahan.pack();
        
        if (dekstopPaneChild.getAllFrames().length == 0)
        {
            dekstopPaneChild.add(frmKelasPerkuliahan);
            frmKelasPerkuliahan.setVisible(true);
        }
        else
        {
            dekstopPaneChild.remove(0);
            dekstopPaneChild.add(frmKelasPerkuliahan);
            frmKelasPerkuliahan.setVisible(true);
            revalidate();
            repaint();
        }
        
        try 
        {
            frmKelasPerkuliahan.setMaximum(true);
        }
        catch (PropertyVetoException ex)
        {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuKelasPerkuliahanActionPerformed

    private void menuMatakuliahPerkuliahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMatakuliahPerkuliahanActionPerformed
        MatakuliahPerkuliahanFrame frmMatakuliahPerkuliahan = new MatakuliahPerkuliahanFrame();
        frmMatakuliahPerkuliahan.pack();
        
        if (dekstopPaneChild.getAllFrames().length == 0)
        {
            dekstopPaneChild.add(frmMatakuliahPerkuliahan);
            frmMatakuliahPerkuliahan.setVisible(true);
        }
        else
        {
            dekstopPaneChild.remove(0);
            dekstopPaneChild.add(frmMatakuliahPerkuliahan);
            frmMatakuliahPerkuliahan.setVisible(true);
            revalidate();
            repaint();
        }
        
        try 
        {
            frmMatakuliahPerkuliahan.setMaximum(true);
        }
        catch (PropertyVetoException ex)
        {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuMatakuliahPerkuliahanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dekstopPaneChild;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuKelasPerkuliahan;
    private javax.swing.JMenuItem menuMatakuliahPerkuliahan;
    // End of variables declaration//GEN-END:variables
}
